#! /bin/sh

g++ -std=c++11 *.cpp litehtml/containers/linux/*.cpp -o litebrowser \
	`pkg-config --cflags --libs cairo` \
	`pkg-config --cflags --libs fontconfig` \
	`pkg-config --cflags --libs gtkmm-3.0` \
	`pkg-config --cflags --libs libcurl` \
	-I ./litehtml/include -L ./litehtml -llitehtml -lPocoFoundation

